[registers.ACTLR_EL1]
write = "unsafe"
[registers.ACTLR_EL2]
write = "unsafe"
[registers.AFSR0_EL1]
write = "unsafe"
[registers.AFSR0_EL2]
write = "unsafe"
[registers.AFSR1_EL1]
write = "unsafe"
[registers.AFSR1_EL2]
write = "unsafe"
[registers.AMAIR_EL1]
write = "unsafe"
[registers.AMAIR_EL2]
write = "unsafe"
[registers.CCSIDR_EL1]
[registers.CLIDR_EL1.field_descriptions]
LoC = "Level of Coherence for the cache hierarchy."

[registers.CNTHCTL_EL2]
[registers.CNTVOFF_EL2]
[registers.CONTEXTIDR_EL1]
[registers.CONTEXTIDR_EL2]
[registers.CPACR_EL1]
[registers.CPTR_EL2]
[registers.CPTR_EL3]
[registers.CSSELR_EL1]
[registers.CTR_EL0]
[registers.DIT]
[registers.ELR_EL1]
[registers.ELR_EL2]
[registers.ESR_EL1]
[registers.ESR_EL2]
[registers.ESR_EL3]
[registers.FAR_EL1]
[registers.FAR_EL2]
[registers.GCSCR_EL1]
[registers.GCSCR_EL2]
[registers.HACR_EL2]
[registers.HCR_EL2]
[registers.HCRX_EL2]
[registers.HPFAR_EL2]
[registers.HSTR_EL2]
[registers.ICC_SRE_EL1]
[registers.ICC_SRE_EL2]
[registers.ICC_SRE_EL3]
write_safety_doc = "The SRE bit of `icc_sre_el3` must not be changed from 1 to 0, as this can result in unpredictable behaviour."

[registers.ICH_HCR_EL2]
[registers.ICH_VMCR_EL2]
[registers.ID_AA64DFR0_EL1]
[registers.ID_AA64DFR1_EL1]
[registers.ID_AA64MMFR1_EL1]
[registers.ID_AA64MMFR2_EL1]
[registers.ID_AA64MMFR3_EL1]
[registers.ID_AA64PFR0_EL1]
[registers.ID_AA64PFR1_EL1]
[registers.ISR_EL1]
[registers.MAIR_EL1]
[registers.MAIR_EL2]
[registers.MAIR_EL3]
write_safety_doc = "The caller must ensure that `value` is a correct and safe configuration value for the EL3 memory attribute indirection register."

[registers.MDCCINT_EL1]
[registers.MDCR_EL2]
[registers.MDCR_EL3]
[registers.MDSCR_EL1]
[registers.MIDR_EL1]
[registers.MPAM2_EL2]
[registers.MPAM3_EL3]
[registers.MPAMHCR_EL2]
[registers.MPAMIDR_EL1]
[registers.MPIDR_EL1]
[registers.PAR_EL1]
[registers.PMCR_EL0]
[registers.SCR_EL3.field_descriptions]
NS = "Non-secure."
IRQ = "Take physical IRQs at EL3."
FIQ = "Take physical FIQs at EL3."
EA = "Take external abort and SError exceptions at EL3."
SMD = "Disable SMC instructions."
HCE = "Enable HVC instructions."
SIF = "Disable execution from non-secure memory."
RW = "Enable AArch64 in lower ELs."
ST = "Trap physical secure timer to EL3."
TWI = "Trap WFI to EL3."
TWE = "Trap WFE to EL3."
TLOR = "Trap LOR register access to EL3."
TERR = "Trap error record register access to EL3."
APK = "Don't trap PAC key registers to EL3."
API = "Don't trap PAuth instructions to EL3."
EEL2 = "Enable Secure EL2."
EASE = "Synchronous external aborts are taken as SErrors."
NMEA = "Take SError exceptions at EL3."
FIEN = "Enable fault injection at lower ELs."
TID3 = "Trap ID group 3 registers to EL3."
TID5 = "Trap ID group 5 register to EL3."
EnSCXT = "Enable SCXT at lower ELs."
ATA = "Enable memory tagging at lower ELs."
FGTEn = "Enable fine-grained traps to EL2."
ECVEn = "Enable access to CNTPOFF_EL2."
TWEDEn = "Enable a configurable delay for WFE traps."
TME = "Enable access to TME at lower ELs."
AMVOFFEN = "Enable acivity monitors virtual offsets."
EnAS0 = "Enable ST64BV0 at lower ELs."
ADEn = "Enable ACCDATA_EL1 at lower ELs."
HXEn = "Enable HCRX_EL2."
GCSEn = "Enable gaurded control stack."
TRNDR = "Trap RNDR and RNDRRS to EL3."
EnTP2 = "Enable TPIDR2_EL0 at lower ELs."
RCWMASKEn = "Enable RCW and RCWS mask registers at lower ELs."
TCR2En = "Enable TCR2_ELx registers at lower ELs."
SCTLR2En = "Enable SCTLR2_ELx rogisters at lower ELs."
PIEn = "Enable permission indirection and overlay registers at lower ELs."
AIEn = "Enable MAIR2_ELx and AMAIR2_ELx at lower ELs."
D128En = "Enable 128-bit system registers at  lower ELs."
GPF = "Route GPFs to EL3."
MECEn = "Enable MECID registers at EL2."
EnFPM = "Enable access to FPMR at lower ELs."
TMEA = "Take synchronous external abort and physical SError exception to EL3."
TWERR = "Trap writes to Error Record registers to EL3."
PFAREn = "Enable access to physical fault address registers at lower ELs."
SRMASKEn = "Enable access to mask registers at lower ELs."
EnIDCP128 = "Enable implementation-defined 128-bit system registers."
DSE = "A delegated SError exception is pending."
EnDSE = "Enable delegated SError exceptions."
FGTEn2 = "Enable fine-grained traps to EL2."
HDBSSEn = "Enable HDBSSBR_EL2 and HDBSSPROD_EL2 registers at EL2."
HACDBSEn = "Enable HACDBSBR_EL2 and HACDBSCONS_EL2 registers at EL2."
NSE = "Non-secure realm world bit."

[registers.SCTLR_EL1]
[registers.SCTLR_EL2]
[registers.SCTLR_EL3]
write_safety_doc = "The caller must ensure that `value` is a correct and safe configuration value for the EL3 system control register."

[registers.SP_EL1]
[registers.SP_EL2]
[registers.SPSR_EL1]
[registers.SPSR_EL2]
[registers.TCR_EL1]
[registers.TCR_EL2]
[registers.TCR_EL3]
write_safety_doc = "The caller must ensure that `value` is a correct and safe configuration value for the EL3 translation control register."

[registers.TPIDR_EL0]
[registers.TPIDR_EL1]
[registers.TPIDR_EL2]
[registers.TPIDRRO_EL0]
[registers.TTBR0_EL1]
[registers.TTBR0_EL2]
[registers.TTBR0_EL3]
write_safety_doc = "The caller must ensure that `value` is a valid base address for the EL3 translation table: it must be page-aligned, and must point to a stage 1 translation table in the EL3 translation regime."

[registers.TTBR1_EL1]
[registers.TTBR1_EL2]
[registers.VBAR_EL1]
[registers.VBAR_EL2]
[registers.VDISR_EL2]
[registers.VMPIDR_EL2]
[registers.VPIDR_EL2]
[registers.VSESR_EL2]
[registers.VTCR_EL2]
[registers.VTTBR_EL2]

[registers.CNTFRQ_EL0]
write = "safe"
